jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mcdb?useUnicode=true&amp;charaterEncoding=utf-8
  username: root
  password: 
  maxActive: 3
  maxIdle: 30
  minIdle: 5
  maxWait: 3000
  validationQuery: /* ping */ select 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: -1
spring:
  datasource:
    schema: classpath:/data/mysql/schema.sql
    data: classpath:/data/hsqldb/data.sql